- name: Detect Docker root directory
  ansible.builtin.command:
    cmd: "docker info --format {{ '{{.DockerRootDir}}' }}"
  register: docker_facts_info
  changed_when: false

- name: Expose Docker facts
  ansible.builtin.set_fact:
    docker_facts_root_dir: "{{ docker_facts_info.stdout }}"
    cacheable: true
