- name: Include vars - Vault
  ansible.builtin.include_vars:
    file: "{{ zabbix_agent.vault_file | default('empty.yaml') }}"
    name: zabbix_agent_instc_vault

- name: Include vars - Config
  ansible.builtin.include_vars:
    file: "{{ zabbix_agent.config_file }}"
    name: zabbix_agent_instc_config

- name: Set OS facts
  ansible.builtin.set_fact:
    zabbix_os_type: "{{ ansible_facts.system | lower }}"
    zabbix_os_family: "{{ ansible_facts.os_family | lower }}"

- name: OS type support check
  ansible.builtin.assert:
    that: zabbix_os_type == 'linux'
    success_msg: "Supported OS type."
    fail_msg: "Unsupported OS type: {{ zabbix_os_type }}."
    quiet: true

- name: OS family support check
  ansible.builtin.assert:
    that: zabbix_os_family == 'debian'
    success_msg: "Supported OS family."
    fail_msg: "Unsupported OS family: {{ zabbix_os_family }}."
    quiet: true

- name: Install package
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present

- name: Stop and disable service
  ansible.builtin.service:
    name: zabbix-agent2
    state: stopped
    enabled: false

- name: Includes shared tasks
  ansible.builtin.import_tasks: deploy_shared_core.yaml

- name: Create script directory
  ansible.builtin.file:
    path: "{{ zabbix_dir.agent.scripts }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy agent configuration
  ansible.builtin.template:
    src: templates/agent/zabbix_agent2.conf.j2
    dest: "{{ zabbix_dir.conf }}/zabbix_agent2.conf"
    owner: root
    group: "{{ zabbix_user.name }}"
    mode: "0640"

- name: Add PSK file
  when: zabbix_agent_instc_config.connection.psk is defined
  ansible.builtin.copy:
    dest: "{{ zabbix_agent_instc_config.connection.psk.key_file }}"
    content: "{{ zabbix_agent_instc_config.connection.psk.key }}"
    owner: "root"
    group: "{{ zabbix_user.name }}"
    mode: "0640"

- name: Remove rotate log configuration
  ansible.builtin.file:
    path: /etc/logrotate.d/zabbix-agent2
    state: absent

- name: Deploy configuration - Rotate log files
  ansible.builtin.template:
    src: templates/agent/logrotate.j2
    dest: "/etc/logrotate.d/zabbix-agent"
    owner: root
    group: root
    mode: "0644"

- name: Start and enable service
  ansible.builtin.service:
    name: zabbix-agent2
    state: started
    enabled: true
