- name: Download signing key
  ansible.builtin.get_url:
    url: https://nginx.org/keys/nginx_signing.key
    dest: /tmp/nginx.gpg.asc
    owner: root
    group: root
    mode: "0644"

- name: Install signing key
  ansible.builtin.command:
    cmd: "gpg --dearmor --yes -o {{ nginx_repo_gpgkey_file }} /tmp/nginx.gpg.asc"
  changed_when: true

- name: Install APT repository
  ansible.builtin.template:
    src: templates/apt.sources.j2
    dest: /etc/apt/sources.list.d/nginx.sources
    owner: root
    group: root
    mode: "0644"

- name: Synchronize APT package information
  ansible.builtin.apt:
    update_cache: true
