# Frequency
daily

# Rotation
su root adm
olddir archived

# File selection
missingok
notifempty
maxage 180

# Files and Folders
create
createolddir 750 root adm

# Compression
compress
delaycompress

# Filenames
dateext
dateformat -%Y%m%d

# Additional config files
include /etc/logrotate.d

