# If present, the Zabbix Server will be deployed and configured.
zabbix_server:
  # Required.
  # Referenced by "zabbix_srv_instc_config".
  config_file: config.yaml

# If present, the Zabbix Agent will be deployed and configured.
zabbix_agent:
  # Required.
  # Referenced by "zabbix_agent_instc_config".
  config_file: config.yaml
  # Referenced by "zabbix_agent_instc_vault".
  vault_file: vault.yaml
