- name: Set OS facts
  ansible.builtin.set_fact:
    timezone_os_type: "{{ ansible_facts.system | lower }}"

- name: OS type support check
  ansible.builtin.assert:
    that: timezone_os_type == 'linux'
    success_msg: "Supported OS type."
    fail_msg: "Unsupported OS type: {{ timezone_os_type }}."
    quiet: true

- name: Set system timezone
  community.general.timezone:
    name: "{{ timezone_name }}"
    hwclock: UTC
