freeradius_repo_key_file: /usr/share/keyrings/inkbridge-packages.gpg

freeradius_repo_pkgs_domain: packages.inkbridgenetworks.com
freeradius_repo_key_url: https://{{ freeradius_repo_pkgs_domain }}/pgp/packages.networkradius.com.asc
