- name: Configure static table
  when: ansible_facts.system == "Linux"
  block:
    - name: Set Cloud-init file
      when: hosts_table_cloud_init | default(false)
      ansible.builtin.set_fact:
        hosts_table_cloud_init_file: "/etc/cloud/templates/hosts.{{ ansible_facts.os_family | lower }}.tmpl"

    - name: Set static table lookup for hostnames
      ansible.builtin.template:
        src: templates/hosts.j2
        dest: "{{ hosts_table_cloud_init_file | default('/etc/hosts') }}"
        owner: root
        group: root
        mode: "0644"
