- name: Install packages
  ansible.builtin.dnf:
    name:
      - "freeradius{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-krb5{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-ldap{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-python{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-rest{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-utils{{ freeradius_ctx.pkg_version | default('') }}"
    state: present

- name: Stop and disable service
  ansible.builtin.service:
    name: radiusd
    state: stopped
    enabled: false

- name: Remove default system user
  ansible.builtin.user:
    name: radiusd
    state: absent

- name: Remove default system group
  ansible.builtin.group:
    name: radiusd
    state: absent

- name: Remove default configuration
  ansible.builtin.file:
    path: /etc/raddb
    state: absent

- name: Create Systemd directory - Override
  ansible.builtin.file:
    path: /etc/systemd/system/radiusd.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Systemd service - Override
  ansible.builtin.template:
    src: templates/systemd.conf.j2
    dest: /etc/systemd/system/radiusd.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
