- name: Install packages
  ansible.builtin.dnf:
    name:
      - "freeradius{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-krb5{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-ldap{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-python{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-rest{{ freeradius_ctx.pkg_version | default('') }}"
      - "freeradius-utils{{ freeradius_ctx.pkg_version | default('') }}"
    state: present

- name: Create alias - Configuration directory
  ansible.builtin.file:
    src: "{{ freeradius_conf_dir }}"
    dest: /etc/freeradius
    state: link
    owner: root
    group: root

- name: Remove default directory
  ansible.builtin.file:
    path: "{{ dir }}"
    state: absent
  loop:
    - /var/lib/radiusd
    - /var/log/radius
  loop_control:
    loop_var: dir
    label: "{{ dir }}"
