- name: Configure TLS/SSL directory
  when: ansible_facts.system == "Linux"
  block:
    - name: Create system groups
      ansible.builtin.group:
        name: "{{ tls_directory_system.name }}"
        gid: "{{ tls_directory_system.id }}"
        system: true
        state: present

    - name: Create directory - Certificates
      ansible.builtin.file:
        path: "{{ tls_directory_base_dir }}/certs"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create directory - Keys
      ansible.builtin.file:
        path: "{{ tls_directory_base_dir }}/private"
        state: directory
        owner: root
        group: "{{ tls_directory_system.name }}"
        mode: "0750"

    - name: Create directory - Passphrases
      ansible.builtin.file:
        path: "{{ tls_directory_base_dir }}/passphrases"
        state: directory
        owner: root
        group: "{{ tls_directory_system.name }}"
        mode: "0750"
