- name: Set OS facts
  ansible.builtin.set_fact:
    fluentbit_repo_os_type: "{{ ansible_facts.system | lower }}"
    fluentbit_repo_os_family: "{{ ansible_facts.os_family | lower }}"

- name: OS support check - Type
  ansible.builtin.assert:
    that: fluentbit_repo_os_type == 'linux'
    success_msg: "Supported OS type."
    fail_msg: "Unsupported OS type: {{ fluentbit_repo_os_type }}."
    quiet: true

- name: OS support check - Family
  ansible.builtin.assert:
    that: "fluentbit_repo_os_family in ['debian', 'redhat']"
    success_msg: "Supported OS family."
    fail_msg: "Unsupported OS family: {{ fluentbit_repo_os_family }}."
    quiet: true

- name: Includes OS based tasks
  ansible.builtin.include_tasks: "{{ fluentbit_repo_os_type }}_{{ fluentbit_repo_os_family }}.yaml"
