- name: Set OS family
  ansible.builtin.set_fact:
    fluentbit_repo_os_family: "{{ ansible_facts.os_family | lower }}"

- name: OS support check
  ansible.builtin.assert:
    that: "fluentbit_repo_os_family in ['debian']"
    success_msg: "Supported OS family."
    fail_msg: "Unsupported OS family."
    quiet: true

- name: Include OS family tasks
  ansible.builtin.include_tasks: "{{ fluentbit_repo_os_family }}.yaml"
