- name: Set OS facts
  ansible.builtin.set_fact:
    fluentbit_os_type: "{{ ansible_facts.system | lower }}"
    fluentbit_os_family: "{{ ansible_facts.os_family | lower }}"

- name: OS support check - Type
  ansible.builtin.assert:
    that: fluentbit_os_type == 'linux'
    success_msg: "Supported OS type."
    fail_msg: "Unsupported OS type: {{ fluentbit_os_type }}."
    quiet: true

- name: OS support check - Family
  ansible.builtin.assert:
    that: "fluentbit_os_family in ['debian', 'redhat']"
    success_msg: "Supported OS family."
    fail_msg: "Unsupported OS family: {{ fluentbit_os_family }}."
    quiet: true

- name: Install package
  ansible.builtin.package:
    name: "fluent-bit{{ fluentbit_config.pkg_version | default('') }}"
    state: present

- name: Stop service
  ansible.builtin.service:
    name: fluent-bit
    state: stopped
    enabled: false

- name: Remove classic configuration files
  ansible.builtin.file:
    path: "{{ fluentbit_dir.conf }}/{{ filename }}"
    state: absent
  loop:
    - fluent-bit.conf
    - parsers.conf
    - plugins.conf
  loop_control:
    loop_var: filename
    label: "{{ filename }}"

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ fluentbit_dir.conf }}"
    - "{{ fluentbit_dir.conf }}/inputs"
    - "{{ fluentbit_dir.conf }}/filters"
  loop_control:
    loop_var: dir
    label: "{{ dir }}"

- name: Create directory
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
  loop:
    - "{{ fluentbit_dir.data }}/storage"
    - "{{ fluentbit_dir.logs }}"
    - "{{ fluentbit_dir.logs }}/dead-letter"
  loop_control:
    loop_var: dir
    label: "{{ dir }}"

- name: Copy base configuration
  ansible.builtin.copy:
    src: files/
    dest: "{{ fluentbit_dir.conf }}"
    owner: root
    group: root
    mode: "0644"
    directory_mode: "0755"

- name: Deploy configuration file
  ansible.builtin.template:
    src: templates/fluent-bit.yaml.j2
    dest: "{{ fluentbit_dir.conf }}/fluent-bit.yaml"
    owner: root
    group: root
    mode: "0644"

- name: Deploy inputs configuration
  ansible.builtin.template:
    src: "templates/inputs/{{ filename }}.yaml.j2"
    dest: "{{ fluentbit_dir.conf }}/inputs/{{ filename }}.yaml"
    owner: root
    group: root
    mode: "0644"
  loop:
    - fluentbit-logs
  loop_control:
    loop_var: filename
    label: "{{ filename }}"

- name: Deploy configuration - Output
  ansible.builtin.template:
    src: "templates/outputs.yaml.j2"
    dest: "{{ fluentbit_dir.conf }}/outputs.yaml"
    owner: root
    group: root
    mode: "0640"

- name: Create Systemd directory - Override
  ansible.builtin.file:
    path: /etc/systemd/system/fluent-bit.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Systemd service - Override
  ansible.builtin.template:
    src: templates/systemd.conf.j2
    dest: /etc/systemd/system/fluent-bit.service.d/override.conf
    owner: root
    group: root
    mode: "0644"

- name: Deploy logrotate configuration
  ansible.builtin.template:
    src: templates/logrotate.j2
    dest: /etc/logrotate.d/fluent-bit
    owner: root
    group: root
    mode: "0644"

- name: Start service
  ansible.builtin.service:
    name: fluent-bit
    state: started
    enabled: true
