# FastCGI settings


fastcgi_connect_timeout 30;
fastcgi_send_timeout 90s;
fastcgi_read_timeout 90s;

fastcgi_buffers 16 16k;
fastcgi_buffer_size 16k;
fastcgi_busy_buffers_size 16k;
fastcgi_temp_file_write_size 32k;

fastcgi_ignore_client_abort off;
fastcgi_intercept_errors off;
